version: 1.2
tools:
   - name: test12
     subclass: cwl
     primaryDescriptorPath: /tools/Dockstore.cwl
   - name: test34
     subclass: wdl
     primaryDescriptorPath: /tools/Dockstore.wdl
     name: wdl
workflows:
   - name: test34
     subclass: cwl
     primaryDescriptorPath: /workflows/HelloWorld.cwl
     publish: true
